remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: S. Mahdi H. Miangoleh
description: "mahdi_miangoleh ατ sfu δøτ ca" 
logo: ./mypic.gif
google_analytics: UA-199229816-1
